name: ğŸ–¤ GA-Misc - Black Check

on:
  pull_request:
    paths-ignore:
      - ".github/**"
    types: [opened, reopened, synchronize]

jobs:
  GA-Misc-Check-Black:
    name: ğŸ–¤ Run Black
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§ Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ğŸ” Get all changed Python files
        id: changed-file-list
        run: |
          echo "changed_files=$(git diff --name-only --diff-filter=ACMRT --merge-base origin/master | grep -E '\.py$' | xargs)" >> $GITHUB_OUTPUT

      - name: ğŸ Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: ğŸ§™â€â™‚ï¸ Run Black format checks
        if: steps.changed-file-list.outputs.changed_files != ''
        run: |
          pip install black
          black --check --diff ${{ steps.changed-file-list.outputs.changed_files }}
